name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2

      - name: Install Tor
        run: sudo apt-get install -y tor

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        working-directory: ./tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./tools
        env:
          DIR_AUTH_PASSWORD: dummy
        run: |
          make cache
          python -m pytest

  test-makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Tor
        run: sudo apt-get install -y tor

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Makefile
        working-directory: ./tools
        env:
          DIR_AUTH_PASSWORD: dummy
        run: |
          make cache
          make update_cache_churn
